topic_list_show_usernames:
  default: false
  type: bool
  required: true

lien_gestion_compte:
  default: ""
  type: string
  validations:
    url: true

leaderboard_id:
  default: 7
  type: integer

blocks:
  default:
    [
      { "order": 1, "blocks": [{ "name": "profile", "size": "4w" }] },
    ]
  type: objects
  schema:
    name: row
    properties:
      order:
        default: 0
        type: integer
      blocks:
        type: objects
        schema:
          name: block
          properties:
            name:
              type: enum
              choices:
                - profile
                - cta
              required: true
            size:
              type: enum
              required: true
              choices:
                - 2x2
                - 4x4
                - 4x2
                - 4w
                - 2x1
                - 1x1
            title:
              default: ""
              type: string
              validations:
                min: 0
                max: 26
            description:
              default: ""
              type: string
              validations:
                min: 0
                max: 140
            cta:
              default: ""
              type: string
              validations:
                min: 0
                max: 26
            url:
              default: ""
              type: string
              validations:
                url: true
            count:
              default: 5
              type: integer
              validations:
                min: 1
                max: 12
            period:
              default: weekly
              type: enum
              choices:
                - all
                - yearly
                - quarterly
                - monthly
                - weekly
                - daily
          allOf:
            - if:
                properties:
                  block:
                    const: profile
              then:
                properties:
                  size:
                    choices:
                      - 2x2
                      - 4x4
                    default: 2x2
                  period:
                    type: null

blocks_border_radius:
  default: "xl"
  type: enum
  choices:
    - xs
    - sm
    - md
    - lg
    - xl
    - 2xl
    - 3xl
    - full

blocks_top:
  default:
    [
      {
        "blocks":
          [],
      },
    ]
  type: objects
  schema:
    name: row
    properties:
      order:
        default: 0
        type: integer
      blocks:
        type: objects
        schema:
          name: block
          properties:
            name:
              type: enum
              choices:
                - banner
              required: true
            size:
              type: enum
              required: true
              choices:
                - 12w
            title:
              default: ""
              type: string
              validations:
                min: 0
                max: 26
            description:
              default: ""
              type: string
              validations:
                min: 0
                max: 140
            ctas:
              default: []
              type: objects
              schema:
                name: cta
                properties:
                  label:
                    default: ""
                    type: string
                    validations:
                      min: 0
                      max: 52
                  url:
                    default: ""
                    type: string
                    validations:
                      url: true
                  style:
                    default: primary
                    type: enum
                    required: true
                    choices:
                      - primary
                      - secondary
                      - tertiary
                      - uncontained

blocks_top_image:
  default: ""
  type: string
  validations:
  url: true
