sso_login_link:
  default: ""
  type: string
  validations:
    url: true

account_management_link:
  default: ""
  type: string
  validations:
    url: true

didomi_key:
  default: ""
  type: string
  validations:
    min: 0
    max: 256

gtm_id:
  default: ""
  type: string
  validations:
    min: 0
    max: 256
